service: realtimeService

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  region: us-east-1
  role: arn:aws:iam::984261700405:role/service-role/dev

functions:
  greeting:
    handler: handler.greeting
    events:
      - http:
          path: /
          method: get
  api:
    handler: handler.graphql
    vpc:
      securityGroupIds:
        - sg-a90c82d6
      subnetIds:
        - subnet-b9495994
        - subnet-5c824114
        - subnet-232b2478
        - subnet-de5d14bb
    events:
      - http:
          path: /graphql
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - clientId
              - Authorization
          integration: lambda-proxy
      - http:
          path: /graphql
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - clientId
              - Authorization
          integration: lambda-proxy