service: wernerService

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  region: us-west-2

functions:
  greeting:
    handler: handler.greeting
    events:
      - http:
          path: /
          method: get
  api:
    handler: handler.graphql
    vpc:
      securityGroupIds:
        - sg-87ba56fc
      subnetIds:
        - subnet-41bbdc26
        - subnet-c591288c
        - subnet-88190ad0
    events:
      - http:
          path: /graphql
          method: get
          cors: true
          integration: lambda-proxy
      - http:
          path: /graphql
          method: post
          cors: true
          integration: lambda-proxy