service: realtimeService

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  region: us-east-1
  role: arn:aws:iam::984261700405:role/service-role/dev

functions:
  greeting:
    handler: handler.greeting
    events:
      - http:
          path: /
          method: get
  api:
    handler: handler.graphql
    vpc:
      securityGroupIds:
        - sg-6040211f
      subnetIds:
        - subnet-9e383cc5
        - subnet-40ab5308
        - subnet-3889fc04
        - subnet-8d5f1ce8
        - subnet-fdeae3d0
    events:
      - http:
          path: /graphql
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - clientId
              - Authorization
          integration: lambda-proxy
      - http:
          path: /graphql
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - clientId
              - Authorization
          integration: lambda-proxy